apiVersion: v1 
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-api-configmap
data:
  Mongo__DataBase: {{ .Values.api.mongodb.databaseName }}
  Mongo__Host: {{ .Release.Name }}-mongo-service
  Mongo__Port: "27017"






 
