apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-ellison-net-cert
spec:
  secretName: ellison-net-secret
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-homolog
  dnsNames:
    - "ellison.net"
    